### ISSUE TITLE
visibleAtInit overlaps first item

### ISSUE THREAD

**Issue by behelit** [lnicolet/HiddenSearchWithRecyclerView#3] opened 2019-02-21 06:08 UTC
When specifying visibleAtInit it overlaps first item in the recycler list.
Is it possible to use visibleAtInit without it overlapping the first item?
I will try forcing a scroll to the top but that isn't ideal.

I think this library is great btw.

Edit: Sorry, I think this may be due to the way I load the recycler content after initialization (because it's a long slow load), will investigate.

**Comment by lucanicoletti** [comment] 2019-02-23 12:20
@behelit have you solved it? Otherwise, I'll have a look into it, can you post some code?

**Comment by behelit** [comment] 2019-02-24 22:53
Sorry, I didn't look into solving it.
In your sample app, if you select the "Show at init example" button, you can see that the first visible item is 'ipsum', while 'Lorem' is behind the searchview.
Maybe force scrolling to the top on load could workaround this.

**Comment by lucanicoletti** [comment] 2019-02-26 14:07
Hello,

I investigated and reproduced the error.
It is being fixed in [Version 0.0.3](https://bintray.com/lnicolet/HiddenSearchWithRecyclerView/HiddenSearchWithRecyclerView/0.0.3), please update the library version in your project and come back if the problem is not fixed.

Closing the issue.

**Closed as completed** 2019-02-26 14:07 UTC
Labels: bug
