### ISSUE TITLE
Jump/Snapping items on scroll

### ISSUE THREAD

**Issue by behelit** [lnicolet/HiddenSearchWithRecyclerView#2] opened 2019-02-21 06:01 UTC
It seems to jump when hiding/showing the searchview.
You can see the items be displaced

**Comment by behelit** [comment] 2019-02-21 06:12
Touch seems to get offset as well when it's visible

**Comment by lucanicoletti** [comment] 2019-02-26 14:09
Can you upload a gif showing this issue? Can't reproduce, sorry

**Comment by lucanicoletti** [comment] 2019-05-26 16:18
Closing this as no feedback was given. Feel free to open it again if facing again this problem.
Thanks.

**Closed as completed by lucanicoletti** 2019-05-26 16:18 UTC
